server:
  port: 8080
  servlet:
    context-path: /api/v0

loggin:
  level:
    root: info
  org:
    springframework: info
    hibernate: error

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:springPractice;DB_CLOSE_ON_EXIT=false
#   url: mysql://localhost:3606/monolithic?userSSL=false&serverTimezone=UTC
    username: admin
    password: admin12345
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: admin12345